UPDATE APPROVAL SET APPROVAL_STATUS = 'PROCESSING' WHERE APPROVAL_STATUS = '처리 중';
UPDATE APPROVAL SET APPROVAL_STATUS = 'APPROVED'   WHERE APPROVAL_STATUS = '승인';
UPDATE APPROVAL SET APPROVAL_STATUS = 'REJECTED'   WHERE APPROVAL_STATUS = '반려';
UPDATE APPROVAL SET APPROVAL_STATUS = 'WITHDRAWN'  WHERE APPROVAL_STATUS = '회수';
UPDATE APPROVAL SET APPROVAL_STATUS = 'TEMP_SAVED' WHERE APPROVAL_STATUS = '임시저장';
