UPDATE APPROVER SET APPROVER_STATUS = 'APPROVED' WHERE APPROVER_STATUS = '승인';
UPDATE APPROVER SET APPROVER_STATUS = 'REJECTED' WHERE APPROVER_STATUS = '반려';
UPDATE APPROVER SET APPROVER_STATUS = 'PENDING'  WHERE APPROVER_STATUS = '대기'
                                                      OR APPROVER_STATUS IS NULL
                                                      OR APPROVER_STATUS = '';
